name: bridge_computational_Bootcamp

channels:
  - defaults

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - astropy
  - h5py
  - numpy
  - pandas>=0.19.0
  - scipy
  - seaborn>=0.8.1
  - pip
